name: frontend-workshop-demo

on: 
    push:
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'chore/**'
            - main # don't forget to remove if use normal flow

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-node@v6
          with: 
            node-version: '24.x'
            cache: 'npm'
        - run: npm ci # Clean Install
        - run: npm run lint
